spring:
  datasource:
    url: jdbc:h2:mem:adesa;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop   # Hibernate creates ALL tables for tests/dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: false

  sql:
    init:
      mode: never             # don't run schema*.sql while using Hibernate DDL

  profiles:
    active: "legacy-json"

spring.h2.console.enabled: true
spring.h2.console.path: /h2

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.la.dataservices.adesa_rti: INFO

auth:
  header-name: X-Webhook-Secret
  secret: ${WEBHOOK_SECRET:secret}