spring:
  datasource:
    url: jdbc:h2:mem:adesa;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql

# H2 web console (handy while demoing)
spring.h2.console.enabled: true
spring.h2.console.path: /h2

server:
  port: 8080

logging:
  level:
    root: INFO
    com.la.dataservices.adesa_rti: INFO
