spring:
  datasource:
    url: jdbc:h2:mem:adesa;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: YOUR_SES_SMTP_USERNAME   # replace with AWS SES SMTP user
    password: YOUR_SES_SMTP_PASSWORD   # replace with AWS SES SMTP password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: dev,legacy-json

alerts:
  #to: dev@wavisys.net
  to: bradharper@laserappraiser.com
  from: tst_server@wavisys.net
  enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop   # Hibernate creates ALL tables for tests/dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: false

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql

spring.h2.console.enabled: true
spring.h2.console.path: /h2

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
    com.la.dataservices.adesa_rti: info

auth:
  # header names
  api-key-header-name: X-Webhook-API-Key
  secret-header-name: X-Webhook-Secret  # (secret header)

  # map of apiKey -> expected secret
  clients:
    dev-api-key: dev-secret
    adesa-rti-test: adesa-rti-test
    partner-b-key: partner-b-secret

