CREATE TABLE IF NOT EXISTS ADESA_JSON_RTI (
                                                   eventType                 VARCHAR(64)  NOT NULL,
    eventDate                 TIMESTAMP    NOT NULL,
    vehicleId                 BIGINT       NOT NULL,
    vin                       VARCHAR(32)  NOT NULL,
    sellerName                VARCHAR(255),
    "year"                    INT,
    makeName                  VARCHAR(255),
    modelName                 VARCHAR(255),
    seriesName                VARCHAR(255),
    bodyStyleName             VARCHAR(255),
    engineName                VARCHAR(255),
    engineDisplacement        DOUBLE,
    cylinders                 INT,
    transmission              VARCHAR(255),
    drivetrain                VARCHAR(255),
    fuelType                  VARCHAR(64),
    interiorColor             VARCHAR(64),
    exteriorColor             VARCHAR(64),
    vehicleType               VARCHAR(64),
    mileage                   INT,
    unitOfMeasure             VARCHAR(32),
    odometerCondition         VARCHAR(64),
    "state"                   VARCHAR(32),
    postalCode                VARCHAR(16),
    currentHighBid            INT,
    buyNowPrice               INT,
    auctionEndDate            TIMESTAMP,
    primaryImageUrl           VARCHAR(2048),
    vehicleDetailUrl          VARCHAR(2048),
    imageViewerUrl            VARCHAR(2048),
    additionalVehicleImageUrls CLOB,
    sellerAnnouncements       CLOB,
    vehicleParts              CLOB,
    hasPriorPaintwork         BOOLEAN,
    sellerType                VARCHAR(64),
    lotNumber                 VARCHAR(64),
    runNumber                 VARCHAR(64),
    lane                      VARCHAR(64),
    auctionVendor             VARCHAR(128),
    runlistDealerCodes        CLOB,
    liveblockDealerCodes      CLOB,
    dealerblockDealerCodes    CLOB,
    assetType                 VARCHAR(64),
    saleEventType             VARCHAR(64),
    saleEventDate             TIMESTAMP,
    damagesCount              INT,
    damagesAmount             INT,
    damagesItems              CLOB,
    openEqualsReserve         BOOLEAN,
    vehicleGrade              DOUBLE,
    isAutoGrade               BOOLEAN,
    titleState                VARCHAR(32),
    frameDamage               INT,
    tires                     CLOB
    );
