-- auto-generated definition
create table stag.adesa_json
(
    eventType                  nvarchar(32) not null,
    eventDate                  datetime     not null,
    vehicleId                  bigint       not null,
    vin                        nvarchar(17) not null,
    sellerName                 nvarchar(100),
    year                       smallint,
    makeName                   nvarchar(64),
    modelName                  nvarchar(64),
    seriesName                 nvarchar(128),
    bodyStyleName              nvarchar(64),
    engineName                 nvarchar(100),
    engineDisplacement         float,
    cylinders                  tinyint,
    transmission               nvarchar(50),
    drivetrain                 nvarchar(32),
    fuelType                   nvarchar(32),
    interiorColor              nvarchar(120),
    exteriorColor              nvarchar(120),
    vehicleType                nvarchar(32),
    mileage                    int,
    unitOfMeasure              nvarchar(64),
    odometerCondition          nvarchar(1024),
    state                      nvarchar(5),
    postalCode                 nvarchar(10),
    currentHighBid             int,
    buyNowPrice                int,
    auctionEndDate             datetime,
    primaryImageUrl            nvarchar(4000),
    vehicleDetailUrl           nvarchar(1024),
    imageViewerUrl             nvarchar(1024),
    additionalVehicleImageUrls nvarchar(max),
    sellerAnnouncements        nvarchar(4000),
    vehicleParts               nvarchar(max),
    hasPriorPaintwork          nvarchar(5),
    sellerType                 nvarchar(64),
    lotNumber                  nvarchar(255),
    runNumber                  nvarchar(255),
    lane                       nvarchar(10),
    auctionVendor              nvarchar(64),
    runlistDealerCodes         nvarchar(4000),
    liveblockDealerCodes       nvarchar(4000),
    dealerblockDealerCodes     nvarchar(4000),
    assetType                  nvarchar(80),
    saleEventType              nvarchar(64),
    saleEventDate              datetime,
    damages                    nvarchar(4000),
    openEqualsReserve          nvarchar(5),
    dealerblockListingCategory nvarchar(64),
    rlLbListingCategory        nvarchar(64),
    vehicleGrade               float,
    isAutoGrade                nvarchar(5),
    chromeStyleId              int,
    chromeYear                 smallint,
    chromeMake                 nvarchar(64),
    chromeModel                nvarchar(64),
    chromeTrim                 nvarchar(64),
    titleState                 nvarchar(5),
    frameDamage                bit,
    tires                      nvarchar(64),
    iteration                  tinyint,
    inTransitIndicator         nvarchar(5),
    adesaAssurance             nvarchar(5),
    autoCheck                  nvarchar(128),
    inspectionDate             datetime,
    inspectionCompany          nvarchar(64),
    inspectionComments         nvarchar(4000),
    structuralDamage           nvarchar(1024),
    drivable                   nvarchar(1024),
    odors                      nvarchar(1024),
    keys                       nvarchar(1024),
    remotes                    nvarchar(1024),
    manuals                    nvarchar(1024),
    firstRun                   nvarchar(5),
    lastRun                    nvarchar(5),
    pdi                        nvarchar(5),
    psi                        nvarchar(5),
    priceReduced               nvarchar(5),
    thirdPartyCRExists         nvarchar(5),
    country                    tinyint,
    saleEventId                nvarchar(64),
    autobidStartTime           datetime,
    psiEligibilityAutobid      nvarchar(5),
    trim                       nvarchar(128),
    priceUpdated               nvarchar(5),
    stockNumber                int,
    highValueOptions           nvarchar(1024),
    doors                      tinyint,
    statements                 nvarchar(4000),
    smokedIn                   nvarchar(5),
    testDriven                 nvarchar(5),
    amsSiteId                  int
)
    go

create index [ix__stag.adesa_json__eventType]
    on stag.adesa_json (eventType) include (eventDate, vehicleId)
    where [eventType] <> N'vehicleRemoved'
    go

